---
- name: install apache2 on ubuntu
  hosts: ubuntu_webservers
  become: yes

  tasks: 
    - name: install apache
      apt: 
        name: apache2
        state: present

    - name: start and enable apache2
      service: 
        name: apache2
        state: started
        enabled: yes